feat: react18 legacy mode & react17 support
Daydreamer-riri/vite-react-ssg pull request #50
Opened 2024-12-12 02:23 UTC by jesse23

2024-12-12 05:49 UTC, Daydreamer-riri commented
Thanks! I think we can handle the rendering function internally through the react-dom exported version instead of passing `useReact17` in manually by the user: https://github.com/facebook/react/blob/4ff5f5719b348d9d8db14aaa49a48532defb4ab7/packages/react-dom/src/client/ReactDOM.js#L182

Like:
```ts
const isReact18 = Number((version || '').split('.')[0]) > 17;
```

2024-12-12 15:06 UTC, jesse23 commented
@Daydreamer-riri there is a use case for us, we need to use it with React18 with 'Old API', which is a valid case...that is why option is needed.

2024-12-12 15:53 UTC, jesse23 commented
comments addressed 🚀

2024-12-12 16:04 UTC, Daydreamer-riri commented
Thank you for your contribution! It's time for me to go to bed, and I'll review the changes as soon as possible tomorrow. Looking forward to the merger!

2024-12-14 05:37 UTC, Daydreamer-riri commented
I left a comment. You can check it out whenever you are free!

2024-12-17 22:45 UTC, jesse23 commented
@Daydreamer-riri  my bad where is your comments? I scanned the diff and not seeing any...

If it is below, I have changed the boolean to `useLegacyRender` as discussed
https://github.com/Daydreamer-riri/vite-react-ssg/pull/50#issuecomment-2537872356

2024-12-18 06:07 UTC, Daydreamer-riri requested changes

2024-12-18 06:07 UTC, Daydreamer-riri commented
Sorry, I forgot to submit it.

2024-12-20 04:19 UTC, jesse23 commented on README.md
> +- for react17, on top of above, you will need minor update to react and react-dom [example](https://github.com/jesse23/webpack-test-bed/blob/main/scripts/define-react-exports.js) to polyfill the mjs
OK I don't want to hack the repo a lot is my former intention...but let me try to port that and see

2024-12-20 04:34 UTC, Daydreamer-riri commented on README.md
> +- for react17, on top of above, you will need minor update to react and react-dom [example](https://github.com/jesse23/webpack-test-bed/blob/main/scripts/define-react-exports.js) to polyfill the mjs
Haha, I understand. I prefer to make a feature as complete as possible if we're going to support it. If you need any help, please feel free to let me know, and I will do my best to help.

2024-12-20 04:47 UTC, jesse23 commented on README.md
> +- for react17, on top of above, you will need minor update to react and react-dom [example](https://github.com/jesse23/webpack-test-bed/blob/main/scripts/define-react-exports.js) to polyfill the mjs
Yes I'll try to adopt the `import { createRoot } from 'react-dom'` to make it minimum. Will try to have a commit soon

2024-12-20 06:59 UTC, jesse23 commented on README.md
> +- for react17, on top of above, you will need minor update to react and react-dom [example](https://github.com/jesse23/webpack-test-bed/blob/main/scripts/define-react-exports.js) to polyfill the mjs
@Daydreamer-riri I made a simplified version of react-helper, please take a look. I have tested for both r17, r18 compatible and r18

2024-12-22 08:45 UTC, Daydreamer-riri approved these changes

2024-12-22 08:46 UTC, merged